### ISSUE TITLE
.fc-listWeek-button class is missiing from Full Calendar theme style rule

### ISSUE THREAD

**Issue by joelghill** [primefaces/primeng-sass-theme#35]
In `theme-base/components/data/_fullcalendar.scss` the `.fc-listWeek-button` class is missing from the rule that defines button styling (Around line 268 in v16.1.0).

**Comment by cetincakiroglu** [comment]
Hi @joelghill,

Since we removed FullCalendar component from primeng here https://github.com/primefaces/primeng/issues/12152 (v14.2.0). We do not need to fix the issue in v16 since the component doesn't exist anymore in the related version. Because of that, I'm closing the issue and your PR.

For the remaining styles related to fullcalendar component, we'll probably remove that file in upcoming releases from primeng-sass-theme.

Thanks a lot for reporting the issue and contributing to your PR!
