### ISSUE TITLE
Is there a plan to publish a package to npmjs.com?

### ISSUE THREAD

**Issue by laggage** [primefaces/primeng-sass-theme#5]

**Comment by pfaffenrodt** [comment]
Would be nice. So we do not have to copy past all files into projects. Just to change colors.

**Comment by pfaffenrodt** [comment]
@JonET ok cool, i try it. Do you still require the api token?

**Comment by cetincakiroglu** [comment]
Hi all,

It's a good request but we don't have it in our roadmap. It might happen in the future but I cannot promise that. Closing the issue since it's a discussion, you can move this issue to https://github.com/orgs/primefaces/discussions platform to discuss further with the community. 

Thanks a lot for the feedback!
